-- 001_create_medicines_table.sql
-- 남건의 약물/영양제 보관함 관리를 위한 Supabase 데이터베이스 테이블 생성 SQL 파일입니다.
-- 프로젝트 규칙 7 준수: supabase/migrations/ 폴더 내에 001_ 순서 번호를 부여하여 작성되었습니다.

-- 1. medicines (약물 보관함) 테이블 생성
CREATE TABLE IF NOT EXISTS public.medicines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT DEFAULT '의약품',
    ingredients TEXT DEFAULT '',
    selected BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. RLS (Row Level Security) 정책 설정 - 누구나 조회, 추가, 삭제 가능하도록 세팅 (Anon 키 전용)
ALTER TABLE public.medicines ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" 
ON public.medicines FOR SELECT 
USING (true);

CREATE POLICY "Allow public insert access" 
ON public.medicines FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Allow public update access" 
ON public.medicines FOR UPDATE 
USING (true);

CREATE POLICY "Allow public delete access" 
ON public.medicines FOR DELETE 
USING (true);

-- 3. 초기 샘플 데이터 입력 (테스트용)
INSERT INTO public.medicines (name, type, ingredients, selected)
VALUES 
    ('종합비타민 (비타민D 1,000 IU)', '건강기능식품', '비타민D 1000IU, 비타민C 500mg', true),
    ('아스피린장용정 100mg', '의약품', '아스피린 100mg', true)
ON CONFLICT DO NOTHING;
